<?php

require_once 'tests/utils/PHPUnit_PDO_Database_TestCase.php';
require_once 'tests/utils/PHPUnit_ArrayDataSet.php';

require_once 'lib/PDODatabase.php';
require_once 'model/SettingModel.php';

/**
 * Test class for SettingsModel.
 * Generated by PHPUnit on 2012-03-04 at 00:26:03.
 */
class SettingsModelTest extends PHPUnit_PDO_Database_TestCase {
	/**
	 * @var SettingModel
	 */
	protected $object;

	/**
	 * Returns the test dataset.
	 *
	 * @return PHPUnit_Extensions_Database_DataSet_IDataSet
	 */
	protected function getDataSet() {
		return new PHPUnit_ArrayDataSet(array(
			'settings' => array(
				array('id' => 1, 'name' => 'test name', 'value' => 'test value')
			)
		));
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new SettingModel(self::getDb());
		parent::setUp();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers SettingModel::__construct
	 */
	public function test__construct() {
		$this->assertInstanceOf("CharField", $this->object->getField("name"));
		$this->assertInstanceOf("CharField", $this->object->getField("value"));
	}
}

?>
