<?php
namespace Admin\Extension\Template\Decorator;

require_once 'admin/lib/Admin/Extension/Template/Escaper/Escaper.php';
require_once 'admin/lib/Admin/Extension/Template/Decorator/BaseDecorator.php';
require_once 'admin/lib/Admin/Extension/Template/Decorator/ObjectDecorator.php';
require_once 'admin/lib/Admin/Extension/Template/Decorator/IteratorDecorator.php';

/**
 * Test class for IteratorDecorator.
 * Generated by PHPUnit on 2011-12-22 at 17:47:49.
 */
class IteratorDecoratorTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var IteratorDecorator
	 */
	protected $object;

	protected $testArray;
	
	public $calls = 0;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$me      = $this;
		$escaper = new \Admin\Extension\Template\Escaper\Escaper(function($value) use ($me) {
			$me->calls++;
			return $value;
		});
		
		$this->testArray = new \ArrayObject(array(1, 2, null, 'foo', 'bar' => 'baz'));

		$this->object = new IteratorDecorator($escaper, $this->testArray);
	}

	public function testIterating() {
		foreach ($this->object as $key => $value) {
			$this->assertEquals($value, $this->testArray[$key]);
		}
		
		$this->assertEquals(4, $this->calls);
	}
}

?>
