<?php
require_once('config/config.php');
require_once('lib/PDODatabase.php');
require_once('lib/model.lib.php');

/**
 * Test class for Model.
 * Generated by PHPUnit on 2012-02-27 at 21:35:20.
 */
class ModelTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Model
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Model("test", new PDODatabase(DB_DSN, DB_USER, DB_PASS, DB_CHARSET));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Model::__sleep
	 * @todo   Implement test__sleep().
	 */
	public function test__sleep() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::__clone
	 * @todo   Implement test__clone().
	 */
	public function test__clone() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::setDb
	 * @todo   Implement testSetDb().
	 */
	public function testSetDb() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::getDb
	 * @todo   Implement testGetDb().
	 */
	public function testGetDb() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::getFields
	 * @todo   Implement testGetFields().
	 */
	public function testGetFields() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::getArgs
	 * @todo   Implement testGetArgs().
	 */
	public function testGetArgs() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::getData
	 * @todo   Implement testGetData().
	 */
	public function testGetData() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::getPKey
	 * @todo   Implement testGetPKey().
	 */
	public function testGetPKey() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::field
	 */
	public function testField() {
		$this->object->field("testfield", new IntField("testfield", Field::PRIMARY_KEY));
		$this->assertInstanceOf("Field", $this->object->getField("testfield"));
	}

	/**
	 * @covers            Model::field
	 * @expectedException ModelException
	 */
	public function testFieldNamedIdExcept() {
		$this->object->field("id", new IntField("id", Field::PRIMARY_KEY));
	}

	/**
	 * @covers Model::arg
	 * @todo   Implement testArg().
	 */
	public function testArg() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::getField
	 * @todo   Implement testGetField().
	 */
	public function testGetField() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::getFilter
	 * @todo   Implement testGetFilter().
	 */
	public function testGetFilter() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::insert
	 * @todo   Implement testInsert().
	 */
	public function testInsert() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::call
	 * @todo   Implement testCall().
	 */
	public function testCall() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::update
	 * @todo   Implement testUpdate().
	 */
	public function testUpdate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::get
	 * @todo   Implement testGet().
	 */
	public function testGet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::distinct
	 * @todo   Implement testDistinct().
	 */
	public function testDistinct() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::delete
	 * @todo   Implement testDelete().
	 */
	public function testDelete() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::filter
	 * @todo   Implement testFilter().
	 */
	public function testFilter() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::filterSet
	 * @todo   Implement testFilterSet().
	 */
	public function testFilterSet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::exclude
	 * @todo   Implement testExclude().
	 */
	public function testExclude() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::getSql
	 * @todo   Implement testGetSql().
	 */
	public function testGetSql() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::reset
	 * @todo   Implement testReset().
	 */
	public function testReset() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::exec
	 * @todo   Implement testExec().
	 */
	public function testExec() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::lastSql
	 * @todo   Implement testLastSql().
	 */
	public function testLastSql() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::order
	 * @todo   Implement testOrder().
	 */
	public function testOrder() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::filterAll
	 * @todo   Implement testFilterAll().
	 */
	public function testFilterAll() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::all
	 * @todo   Implement testAll().
	 */
	public function testAll() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::filterFields
	 * @todo   Implement testFilterFields().
	 */
	public function testFilterFields() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::filterExpr
	 * @todo   Implement testFilterExpr().
	 */
	public function testFilterExpr() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::definition
	 * @todo   Implement testDefinition().
	 */
	public function testDefinition() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::row
	 * @todo   Implement testRow().
	 */
	public function testRow() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::limit
	 * @todo   Implement testLimit().
	 */
	public function testLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::offset
	 * @todo   Implement testOffset().
	 */
	public function testOffset() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::collection
	 * @todo   Implement testCollection().
	 */
	public function testCollection() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Model::filterOS
	 * @todo   Implement testFilterOS().
	 */
	public function testFilterOS() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}

?>
