<?php
namespace Admin\Extension\Template\Escaper;

require_once 'admin/lib/Admin/Extension/Template/Escaper/Escaper.php';
require_once 'admin/lib/Admin/Extension/Template/Escaper/HtmlEscaper.php';

/**
 * Test class for HtmlEscaper.
 * Generated by PHPUnit on 2011-12-22 at 18:16:14.
 */
class HtmlEscaperTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var HtmlEscaper
	 */
	protected $object;


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new HtmlEscaper();
	}

	public function testEscapeString() {
		$string = '<script>alert(1);</script>';
		$result = $this->object->escapeHtml($string);
		$this->assertEquals(htmlspecialchars($string), $result);
	}
	
	public function testEscapeOther() {
		$this->assertEquals(1, $this->object->escapeHtml(1));
		$this->assertEquals(4.5, $this->object->escapeHtml(4.5));
		$this->assertEquals(null, $this->object->escapeHtml(null));
	}
}

?>
