<?php

require_once 'admin/lib/Admin/Controller.php';
require_once 'admin/lib/Admin/Application.php';

/**
 * Test class for Controller.
 * Generated by PHPUnit on 2011-10-05 at 11:50:47.
 */
class ControllerTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var \Admin\Controller
	 */
	protected $object;
	
	/**
	 * @var \Admin\Application
	 */
	protected $testApp;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->testApp = new \Admin\Application();
		$this->object = new FooController($this->testApp);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	public function test__invoke() {
		$request = new \Admin\Request(array('action' => 'foo'));
		
		$result = $this->callController($request);
		
		$this->assertEquals('bar', $result);
	}
	
	/**
	 * @expectedException InvalidArgumentException
	 */
	public function test__invokeNoMethod() {
		$request = new \Admin\Request(array('action' => 'nomethod'));
		
		$this->callController($request);
	}
	
	/**
	 * @expectedException InvalidArgumentException
	 */
	public function test__invokeNoAction() {
		$request = new \Admin\Request();
		
		$this->callController($request);
	}
	
	private function callController($request) {
		$callable = $this->object;
		return $callable($request);
	}
}

class FooController extends \Admin\Controller {
	public function do_foo() {
		return 'bar';
	}
}

?>
