<?php

require_once 'tests/utils/PHPUnit_PDO_Database_TestCase.php';
require_once 'tests/utils/PHPUnit_ArrayDataSet.php';

require_once 'model/adminaccess.model.php';

/**
 * Test class for AdminAccessModel.
 * Generated by PHPUnit on 2012-03-13 at 03:23:37.
 */
class AdminAccessModelTest extends PHPUnit_PDO_Database_TestCase {
	/**
	 * @var AdminAccessModel
	 */
	protected $object;

	/**
	 * Returns the test dataset.
	 *
	 * @return PHPUnit_Extensions_Database_DataSet_IDataSet
	 */
	protected function getDataSet() {
		return new PHPUnit_ArrayDataSet(array(
			'admin_access' => array(
				array(
					'id' => 1, 'user_id' => 5, 'route_name' => 'some_route_name'
				)
			)
		));
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new AdminAccessModel(self::getDb());
		parent::setUp();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers AdminAccessModel::__construct
	 */
	public function test__construct() {
		$this->assertInstanceOf("IntField", $this->object->getField("id"));
		$this->assertInstanceOf("IntField", $this->object->getField("user_id"));
		$this->assertInstanceOf("CharField", $this->object->getField("route_name"));
	}

	/**
	 * @covers AdminAccessModel::getRouteNames
	 */
	public function testGetRouteNames() {
		$r = $this->object->getRouteNames(5);
		$this->assertInstanceOf('AdminAccessModel', $r);
		$this->assertEquals('some_route_name', $r[0]->route_name);
	}


}

?>
