<?php

require_once 'tests/utils/PHPUnit_PDO_Database_TestCase.php';
require_once 'tests/utils/PHPUnit_ArrayDataSet.php';
require_once 'lib/PDODatabase.php';
require_once 'model/BeachModel.php';

/**
 * Test class for BeachModel.
 * Generated by PHPUnit on 2012-03-03 at 22:00:59.
 */
class BeachModelTest extends PHPUnit_PDO_Database_TestCase {
	/**
	 * @var BeachModel
	 */
	protected $object;

	/**
	 * Returns the test dataset.
	 *
	 * @return PHPUnit_Extensions_Database_DataSet_IDataSet
	 */
	protected function getDataSet() {
		return new PHPUnit_ArrayDataSet(array(
			'beach' => array(
				array(
					'id'          => 1,
					'name'        => 'Тестовый пляж',
					'link'        => 'http://github.com/dualavatara/jbfw'
				),
			)
		));
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new BeachModel(self::getDb());
		parent::setUp();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers BeachModel::__construct
	 */
	public function testConstruct() {
		$this->assertInstanceOf("CharField", $this->object->getField("name"));
		$this->assertInstanceOf("CharField", $this->object->getField("link"));
	}
}

?>
