<?php

require_once 'tests/utils/PHPUnit_PDO_Database_TestCase.php';
require_once 'tests/utils/PHPUnit_ArrayDataSet.php';

require_once 'model/CarRentOfficeModel.php';

/**
 * Test class for CarRentOfficeModel.
 * Generated by PHPUnit on 2012-03-13 at 03:03:53.
 */
class CarRentOfficeModelTest extends PHPUnit_PDO_Database_TestCase {
	/**
	 * @var CarRentOfficeModel
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new CarRentOfficeModel(self::getDb());
		parent::setUp();
	}

	/**
	 * Returns the test dataset.
	 *
	 * @return PHPUnit_Extensions_Database_DataSet_IDataSet
	 */
	protected function getDataSet() {
		return new PHPUnit_ArrayDataSet(array(
			'car_rent_office' => array(
				array(
					'id' => 1,
					'name' => 'testname',
					'description' => 'testdescr',
					'percent' => '10.5',
					'customer_id' => '5',
					'rating' => '100'
				)
			)
		));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers CarRentOfficeModel::__construct
	 */
	public function test__construct() {
		$this->assertInstanceOf("IntField", $this->object->getField("id"));
		$this->assertInstanceOf("CharField", $this->object->getField("name"));
		$this->assertInstanceOf("CharField", $this->object->getField("description"));
		$this->assertInstanceOf("RealField", $this->object->getField("percent"));
		$this->assertInstanceOf("IntField", $this->object->getField("customer_id"));
		$this->assertInstanceOf("IntField", $this->object->getField("rating"));
	}
}

?>
