<?php

require_once 'lib/PDODatabase.php';
require_once 'model/CurrencyModel.php';

/**
 * Test class for CurrencyModel.
 * Generated by PHPUnit on 2012-02-28 at 05:07:54.
 */
class CurrencyModelTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var CurrencyModel
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new CurrencyModel(new PDODatabase($GLOBALS['DB_DSN'], $GLOBALS['DB_USER'], $GLOBALS['DB_PASSWD'], 'utf8'));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	public function testConstruct() {
		$this->assertInstanceOf("CharField", $this->object->getField("name"));
		$this->assertInstanceOf("CharField", $this->object->getField("sign"));
		$this->assertInstanceOf("RealField", $this->object->getField("course"));
	}
}

?>
