<?php

require_once 'tests/utils/PHPUnit_PDO_Database_TestCase.php';
require_once 'tests/utils/PHPUnit_ArrayDataSet.php';

require_once 'model/CustomerModel.php';

/**
 * Test class for CustomerModel.
 * Generated by PHPUnit on 2012-03-13 at 02:28:53.
 */
class CustomerModelTest extends PHPUnit_PDO_Database_TestCase {
	/**
	 * @var CustomerModel
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new CustomerModel(self::getDb());
		parent::setUp();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * Returns the test dataset.
	 *
	 * @return PHPUnit_Extensions_Database_DataSet_IDataSet
	 */
	protected function getDataSet() {
		return new PHPUnit_ArrayDataSet(array(
			'customer' => array(
				array(
					'id' => 1,
					'email' => 'test@email.com',
					'name' => 'testname',
					'phone_msk' => 'testphone1',
					'phone_local' => 'testphone2',
					'address' => 'testaddress',
					'country' => 'testcountry',
					'skype' => 'testskype',
					'icq' => 'testicq',
					'admin_note' => 'testnote'
				)
			)
		));
	}

	/**
	 * @covers CustomerModel::__construct
	 */
	public function test__construct() {
		$this->assertInstanceOf("IntField", $this->object->getField("id"));
		$this->assertInstanceOf("CharField", $this->object->getField("email"));
		$this->assertInstanceOf("CharField", $this->object->getField("name"));
		$this->assertInstanceOf("CharField", $this->object->getField("phone_msk"));
		$this->assertInstanceOf("CharField", $this->object->getField("phone_local"));
		$this->assertInstanceOf("CharField", $this->object->getField("address"));
		$this->assertInstanceOf("CharField", $this->object->getField("country"));
		$this->assertInstanceOf("CharField", $this->object->getField("skype"));
		$this->assertInstanceOf("CharField", $this->object->getField("icq"));
		$this->assertInstanceOf("CharField", $this->object->getField("admin_note"));
	}
}

?>
