<?php

require_once 'tests/utils/PHPUnit_PDO_Database_TestCase.php';
require_once 'tests/utils/PHPUnit_ArrayDataSet.php';
require_once 'lib/PDODatabase.php';
require_once 'model/DiscountModel.php';

/**
 * Test class for DiscountModel.
 * Generated by PHPUnit on 2012-03-03 at 06:12:40.
 */
class DiscountModelTest extends PHPUnit_PDO_Database_TestCase {
	/**
	 * @var DiscountModel
	 */
	protected $object;

	/**
	 * Returns the test dataset.
	 *
	 * @return PHPUnit_Extensions_Database_DataSet_IDataSet
	 */
	protected function getDataSet() {
		return new PHPUnit_ArrayDataSet(array('discount' => array(array('id'          => 1,
																		'description' => 'пример описания',
																		'percent'     => '15'),)));
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		parent::setUp();
		$this->object = new DiscountModel(self::getDb());
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers DiscountModel::__construct
	 */
	public function testConstruct() {
		$this->assertInstanceOf("CharField", $this->object->getField("description"));
		$this->assertInstanceOf("RealField", $this->object->getField("percent"));
	}
}

?>
