<?php

require_once 'model/PriceModel.php';
require_once 'lib/PDODatabase.php';

/**
 * Test class for PriceModel.
 * Generated by PHPUnit on 2012-02-28 at 04:26:10.
 */
class PriceModelTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var PriceModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PriceModel(new PDODatabase($GLOBALS['DB_DSN'], $GLOBALS['DB_USER'], $GLOBALS['DB_PASSWD'], "utf8"));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

	public function testConstruct() {
		$this->assertInstanceOf("Field", $this->object->getField("flags"));
		$this->assertInstanceOf("Field", $this->object->getField("start"));
		$this->assertInstanceOf("Field", $this->object->getField("end"));
		$this->assertInstanceOf("Field", $this->object->getField("currency_id"));
		$this->assertInstanceOf("Field", $this->object->getField("value"));
	}
}
?>
